# Hierarchy

Python code can be ordered using the following hierarchy.
Note that some hierarchy levels are not applicable for Jupyter Notebooks but only for "normal" Python code.

## Packages [optional]
A directory conaining .py files (i.e. Modules) and/ or subpackages. A directory becomes a Python Package if the file 

    __init__.py 
    
(which is usually empty) is present.

## Modules
A file containing Python code. It may be top level or inside a Package. A module may contain functions, classes, variables (usually constants) and/ or code.
    
Code inside a Module is automatically executed if the module is imported. Code which should be only executed if the module itself is executed (not by imports from other modules) is protected using the following check:
    
    if __name__ == '__main__':
        code
        
Note that it is perfectly fine in Python to have constants and functions directly in Modules, outside classes (unlike e.g. in Java, where everything must be inside a class). The module-level namespaces avoid naming conflicts.

# Functions

In [1]:
def f(x):
    return x**2

In [2]:
f, type(f)

(<function __main__.f(x)>, function)

In [3]:
f(5)

25

In [4]:
def pow(x,y=2):
    return x**y
    print('I will never be executed')

In [5]:
pow(3, 3), pow(3), pow(y=1, x=42)

(27, 9, 42)

Parameters can be optional if a default value is provided. Optional parameters must be at the end of the function definition.

The function exists at the return statement, code afterwards is not executed.

In [6]:
def void():
    print('hello')

In [7]:
out = void()
print(out)

hello
None


Functions without return statement return None.

In [8]:
def dummy_function():
    pass

If a function (or class) has no content, the pass statement is required.

## Functions as Parameters

In [9]:
import typing
def make_value_table(fun: typing.Callable, xmin=0, xmax=1, steps=10):
    x = [xmin + (xmax-xmin)/steps*i for i in range(steps+1)]
    xy = [(xx, fun(xx)) for xx in x]
    return xy

In [10]:
import math
make_value_table(math.sin, 0, 2*math.pi)

[(0.0, 0.0),
 (0.6283185307179586, 0.5877852522924731),
 (1.2566370614359172, 0.9510565162951535),
 (1.8849555921538759, 0.9510565162951536),
 (2.5132741228718345, 0.5877852522924732),
 (3.141592653589793, 1.2246467991473532e-16),
 (3.7699111843077517, -0.587785252292473),
 (4.39822971502571, -0.9510565162951535),
 (5.026548245743669, -0.9510565162951536),
 (5.654866776461628, -0.5877852522924734),
 (6.283185307179586, -2.4492935982947064e-16)]

In Python, everything is an object. This implies that not only variables and objects, but also functions and classes can be passed as parameters to functions, etc.

## Lambda Functions


In [11]:
my_func = lambda x: x**3
my_func, type(my_func)

(<function __main__.<lambda>(x)>, function)

In [12]:
make_value_table(lambda x: x**2)

[(0.0, 0.0),
 (0.1, 0.010000000000000002),
 (0.2, 0.04000000000000001),
 (0.30000000000000004, 0.09000000000000002),
 (0.4, 0.16000000000000003),
 (0.5, 0.25),
 (0.6000000000000001, 0.3600000000000001),
 (0.7000000000000001, 0.4900000000000001),
 (0.8, 0.6400000000000001),
 (0.9, 0.81),
 (1.0, 1.0)]

The lambda statement is used to create anonymous functions. 
Usually, lambda functions are used when small in-line functions are required, e.g. as function parameters.

In [13]:
xy = make_value_table(lambda x: x**2)
eucl_abs = lambda x, y: math.sqrt(x**2 + y**2)
[eucl_abs(xy[i][0], xy[i][1]) for i in range(11)]

[0.0,
 0.1004987562112089,
 0.20396078054371142,
 0.31320919526731655,
 0.4308131845707604,
 0.5590169943749475,
 0.6997142273814362,
 0.8544588931013594,
 1.024499877989256,
 1.210826164236634,
 1.4142135623730951]

Lambda functions can be defined with more than 1 parameter.

## Args and KWArgs

In [14]:
def print_arguments(*args, **kwargs):
    print(f'positional arguments: {args}')
    print(f'keyword arguments: {kwargs}')

In [15]:
print_arguments(1, 2, 3, 4, a=5, b=6, c=7)

positional arguments: (1, 2, 3, 4)
keyword arguments: {'a': 5, 'b': 6, 'c': 7}


The statement \*args catches all given positional arguments (i.e. arguments without a keyword) and puts them into a tuple.

The statement \*\*kwargs catches all keyword arguments and puts them into a dictionary.

Note that the stars define the syntax, not the names (args, kwargs), the latter are however the usual convention.

This syntax is very useful e.g. when a function passes arguments to a daughter function.

In [16]:
def multiple_caller(func, n, *args, **kwargs):
    res = []
    for i in range(n):
        res.append(func(*args, **kwargs))
    return res

In [17]:
import math
multiple_caller(math.pow, 4, 2, 4)

[16.0, 16.0, 16.0, 16.0]

In [18]:
import json
multiple_caller(json.dumps, 4, [1, 2, 3, {'4': 5, '6': 7}], separators=(',', ':'))

['[1,2,3,{"4":5,"6":7}]',
 '[1,2,3,{"4":5,"6":7}]',
 '[1,2,3,{"4":5,"6":7}]',
 '[1,2,3,{"4":5,"6":7}]']

## Decorators

In [97]:
import datetime
def timeit(func):
    """
    Decorator function to measure elapsed time for a function call.
    Serves only as an example for decorators, better use IPython's %timeit
    """
    def _func(*args, **kwargs): # here is the input function modified
        start_time = datetime.datetime.utcnow()
        res = func(*args, **kwargs)
        end_time = datetime.datetime.utcnow()
        print(f'elapsed time: {end_time - start_time}')
        return res
    return _func

In [98]:
def example_func(n, l):
    return n in l

In [99]:
timeit(example_func)(-1, list(range(10000)))

elapsed time: 0:00:00.000252


False

A decorator function takes an other function as input, modifies it and returnx the modified function.

In [100]:
@timeit
def example_func_with_decorator(n, l):
    return n in l

In [101]:
example_func_with_decorator(-1, list(range(10000)))

elapsed time: 0:00:00.000253


False

The decorator syntax makes it easy to define a funtion which is modified by a decorator function.

### Decorators with Arguments

In [136]:
import numpy as np 
# numpy is explained in an other tutorial, here it is just used for an array
x = np.arange(0,10)

In [130]:
def diff_quotient(func, h=0.001):
    def diff_func(x, *args, **kwargs):
        dfdx = (func(x+h, *args, **kwargs) - func(x, *args, **kwargs)) / h
        return dfdx
    return diff_func

In [133]:
diff_quotient(lambda x: x**2)(x) # should be approx. 2x

array([1.0000e-03, 2.0010e+00, 4.0010e+00, 6.0010e+00, 8.0010e+00,
       1.0001e+01, 1.2001e+01, 1.4001e+01, 1.6001e+01, 1.8001e+01])

In [137]:
diff_quotient(lambda x: x**2, h=1e-6)(x) # should be approx. 2x

array([1.0000000e-06, 2.0000010e+00, 4.0000010e+00, 6.0000010e+00,
       8.0000010e+00, 1.0000001e+01, 1.2000001e+01, 1.4000001e+01,
       1.6000001e+01, 1.8000001e+01])

In [135]:
@diff_quotient
def pow(x, y):
    return x**y

In [129]:
pow(x, 3) # should be approx 3x**2

array([1.00000000e-12, 3.00000300e+00, 1.20000060e+01, 2.70000090e+01,
       4.80000120e+01, 7.50000150e+01, 1.08000018e+02, 1.47000021e+02,
       1.92000024e+02, 2.43000027e+02])

In [139]:
try:
    @diff_quotient(h=1e-6)
    def pow(x, y):
        return x**y
except TypeError as e:
    print(e)

diff_quotient() missing 1 required positional argument: 'func'


A decorator which calculates the difference quotient 

$\frac{Df}{Dx} = \frac{f(x+h) - f(x)}{h}$

Note that the parameter h can be changed from its default value only in the function call syntax, not in the decorator syntax! 
A decorator function takes only exactly one parameter, this is the function to be decorated.

How can we solve this problem?

In [144]:
def diff_quotient_factory(h=0.001):
    def diff_quotient(func):
        def diff_func(x, *args, **kwargs):
            dfdx = (func(x+h, *args, **kwargs) - func(x, *args, **kwargs)) / h
            return dfdx
        return diff_func
    return diff_quotient

In [145]:
x = np.arange(0,10)
diff_quotient_factory(1e-6)(lambda x: x**2)(x) # should be approx. 2x
# note the different location of the h parameter

array([1.0000000e-06, 2.0000010e+00, 4.0000010e+00, 6.0000010e+00,
       8.0000010e+00, 1.0000001e+01, 1.2000001e+01, 1.4000001e+01,
       1.6000001e+01, 1.8000001e+01])

In [146]:
@diff_quotient_factory(h=1e-6)
def pow(x, y):
    return x**y

In [147]:
pow(x, 3) # should be approx 3x**2

array([1.00000000e-12, 3.00000300e+00, 1.20000060e+01, 2.70000090e+01,
       4.80000120e+01, 7.50000150e+01, 1.08000018e+02, 1.47000021e+02,
       1.92000024e+02, 2.43000027e+02])

The solution is the definition of a decorator factory function. This function may take arbitrary parameters and return a decorator function (i.e. a function which itself modifies a function).

Note that the decorator factory pattern is used extensively by some Python libraries, e.g. the Flask web framework (for example the @route() decorator).

# Classes

In [19]:
class Vehicle:
    """example class"""
    def __init__(self, wheels, seats):
        """
        The __init__ method is used for object creation.
        """
        self.wheels = wheels
        self.seats = seats
    def drive(self, km):
        print("driving {} km on {} wheels".format(km, self.wheels))

In [20]:
bicycle = Vehicle(2, 1)
bicycle.drive(10)

driving 10 km on 2 wheels


In [21]:
bicycle.wheels

2

## Inheritance

In [22]:
class Car(Vehicle):
    def __init__(self, seats, power):
        super().__init__(wheels=4, seats=seats) # calls constructuor of parent class
        self.power = power
    def drive(self, km):
        print("driving {} km on {} wheels with {} kW power".format(
            km, self.wheels, self.power))

In [23]:
my_car = Car(5, 150)
my_car.drive(200)

driving 200 km on 4 wheels with 150 kW power


If a method is overwritten in the child class (like init in the example), the method of the parent class can be accessed with super().

### Multiple Inheritance

In [24]:
class PurchaseMixin:
    price = None
    currency = 'EUR'
    nr_owned = 0
    def buy(self, nr=1):
        self.nr_owned += nr
        print("purchased {} piece(s) for {} {}".format(nr, nr*self.price, self.currency))
    def sell(self, nr=1):
        if nr > self.nr_owned:
            raise ValueError('you own less than you want to sell!')
        self.nr_owned -= nr
        print("sold {} piece(s) for {} {}".format(nr, nr*self.price, self.currency))

In [25]:
class PurchasableCar(PurchaseMixin, Car):
    pass

In [26]:
my_cars = PurchasableCar(5, 150)
my_cars.price = 30000
my_cars.buy(2)
my_cars.sell()
my_cars.drive(250)
my_cars.nr_owned

purchased 2 piece(s) for 60000 EUR
sold 1 piece(s) for 30000 EUR
driving 250 km on 4 wheels with 150 kW power


1

Classes in Python may inherit from multiple parent classes. This can be used to add additional features to classes.

### Naming Resolution

In [27]:
class A:
    def __init__(self):
        self.i = 1
        print('init A')
    def func(self, x):
        return x+1
class B:
    def __init__(self):
        self.i = 2
        print('init B')
    def func(self, x):
        return x+2

In [28]:
class AB(A,B):
    pass
class BA(B,A):
    pass

In [29]:
ab = AB()
ba = BA()
ab.func(0), ba.func(0)

init A
init B


(1, 2)

If parent classes have the same methods (including init), the derived class uses the method of the 1st parent.

In [30]:
class AB2(A, B):
    def func(self,x):
        return B.func(self, x)

In [31]:
ab2 = AB2()
ab2.func(0)

init A


2

Methods in the 2nd parent class, which have been overwritten my identically named methods in the 1st parent class, can be called using the parent class name as prefix.

## Property Methods

In [32]:
my_cars.price = 'hello'
my_cars.buy() # output is not what is expected

purchased 1 piece(s) for hello EUR


In languages like C++ and Java one usually implements getter and setter methods for any public property. 
This is discouraged in Python because it creates a lot of boilerplate code.
Instead, properties should be accessed directly.

If it turns out later that logic (like validations, formatting) is required when getting or setting properties, they can be changed in the class definition to property methods without changing the class api.

In [33]:
from numbers import Number
class SafePurchaseMixin(PurchaseMixin):
    _price = None
    
    @property
    def price(self):
        if self._price is None:
            raise ValueError('price not set')
        return self._price
    
    @price.setter
    def price(self, x):
        if not isinstance(x, Number):
            raise TypeError('Price must be numeric')
        if x <= 0:
            raise ValueError('Price must be positive')
        self._price = x
        
    @price.deleter # for completeness, often not required
    def price(self):
        self._price = None

In [34]:
class PurchasableCar2(SafePurchaseMixin, Car):
    pass

In [35]:
my_cars = PurchasableCar2(5, 150)
my_cars.price = 30000 # note that the api is identical to PurchasableCars
my_cars.buy(2)
my_cars.sell()
my_cars.drive(250)
my_cars.nr_owned

purchased 2 piece(s) for 60000 EUR
sold 1 piece(s) for 30000 EUR
driving 250 km on 4 wheels with 150 kW power


1

In [36]:
try:
    my_cars.price = 'hello'
except TypeError as e:
    print(e)

Price must be numeric


In [37]:
del my_cars.price
try:
    print(my_cars.price)
except ValueError as e:
    print(e)

price not set


In the property methods for price, validation has been included without any change of the class api.

## Static Methods

In [38]:
class PurchasableCar3(PurchasableCar2):
    @staticmethod
    def convert_kw_to_hp(kw):
        return 1.36 * kw

In [64]:
PurchasableCar3.convert_kw_to_hp(120)

163.20000000000002

Methods inside a class which do not need any input from the class itself, can (and should) be defined as static methods. This is done as follows:

1. the decorator @staticmethod
2. self is not a parameter of the method

Static mehods can be used analogue to standard object methods. In addition, it they could be called on the class itself, without need to instanciate an object.

# Class Methods

In [65]:
class PurchasableCar4(PurchasableCar3):
    @classmethod
    def from_dict(cls, data):
        obj = cls(seats=data.get('seats'),
                 power=data.get('power'))
        obj.price=data.get('price')
        obj.currency=data.get('currency','EUR')
        return obj

In [73]:
car_data = {'seats': 2, 'power': 250, 'price': 125000}
sports_car = PurchasableCar4.from_dict(car_data)
print(f'''seats: {sports_car.seats}, 
power in hp: {sports_car.convert_kw_to_hp(sports_car.power)},
price: {sports_car.price} {sports_car.currency}''')

seats: 2, 
power in hp: 340.0,
price: 125000 EUR


Class methods are executed on classes, not objects (i.e. instances of classes).
A common use case for class methods are alternative constructors which return class instances.

More about static and class methods here:

https://realpython.com/instance-class-and-static-methods-demystified/

## Dunder Methods

In [39]:
from math import sqrt
class ComplexNumber:
    """
    just as an example, in practice use the built-in complex data type!
    """
    def __init__(self,real, imag=0):
        self.r = real
        self.i = imag
    
    @staticmethod
    def _convert_num(x):
        """
        Converts number or ComplexNumber into real and imaginary part.
        This is an internal method, marked by leading underscore (_).
        """
        if isinstance(x, ComplexNumber):
            r2 = x.r
            i2 = x.i
        else:
            r2 = x
            i2 = 0
        return r2, i2
    
    def __str__(self):
        """Defines string representation of the object."""
        return "{r} + {i} * i".format(r=self.r, i=self.i)
    
    def __repr__(self):
        """Defines a printable representation of the object. 
        Usually __repr__ contains more debugging information than __str__."""
        return "ComplexNumber object, value: {r} + {i} * i".format(r=self.r, i=self.i)
    
    def __add__(self, x):
        r2, i2 = self._convert_num(x)
        return ComplexNumber(self.r + r2, self.i + i2)

    def get_abs_value(self):
        return sqrt(self.r**2 + self.i**2)

In [40]:
c1 = ComplexNumber(1, 2)
print(c1)

1 + 2 * i


The print function implicitly converts the ComplexNumber object into a string, i.e. printing the output of the \_\_str__ method.

In [41]:
c1

ComplexNumber object, value: 1 + 2 * i

In [42]:
c1.r, c1.i, c1.get_abs_value()

(1, 2, 2.23606797749979)

In [43]:
c2 = ComplexNumber(2, 3)
c3 = c1 + c2
print(c3)

3 + 5 * i


In [44]:
print(c1 + 7)

8 + 2 * i


# Namespaces

In [45]:
outside1 = 42
outside2 = 0
def f_bad(x):
    outside2 = x # this is actually a local variable 
                 # which has nothing to do with outside 2 defined before
    print(outside2)
    return x + outside1 # extremely dangerous usage of global variable

In [46]:
outside2

0

In [47]:
f_bad(7), outside2

7


(49, 0)

Variables defined inside a function (or class) are local, i.e. they are only valid inside the function and changes of them do not influence anything outside the function. This is true even if outside variables have the same name (here global2).

Variables defined outside the function, however, can be accessed from inside the function. This is however very dangerous and should be avoided!

In [48]:
def f_even_worse(x):
    global outside2 # makes the variable defined outside changable inside the function
    outside2 = x # the outside variable is actually changed here!
    print(outside2)
    return x + outside1 # extremely dangerous usage of global variable

In [49]:
outside2

0

In [50]:
f_even_worse(7), outside2

7


(49, 7)

The *global* stament makes the variable defined outside changable inside the function. The usage of this pattern is __extremely__ dangerous and must be avoided!

In [51]:
def f_good(x, i):
    print(x)
    return x + i

In [52]:
f_good(7, 42)

7


49

Refactored version of the previous function without implicit usage of variable defined outside the function.

In [53]:
def f_mod_input(i: int, l: list):
    l.append(i)
    i = i*2
    return i

In [54]:
i1 = 42 # basic variable
l1 = [1, 2] # list object
f_mod_input(i1, l1)

84

In [55]:
i1, l1

(42, [1, 2, 42])

Both function parameters (here integer and list) are changed inside the function.

* The basic type (here integer) is however not changed in the outside scope - call by value
* The complex type (here list) is changed in the outside scope by the modification inside the function - call by reference

It is a common source of errors and (in my opinion) a major weakness of Python language that call by value and call by reference are not clearly separated by syntax (like in C (++) where pointers have * as prefix).

Call by reference can be used on purpose to modify objects in outer scope by the function. However, it is safer to explicitly create a new object inside the function, modify that and return it.

In [56]:
def f_safer(i: int, l: list):
    l2 = l.copy() # creates new list object
    l2.append(i)
    i = i*2
    return i, l2

In [57]:
i1 = 42 # basic variable
l1 = [1, 2] # list object
f_safer(i1, l1)

(84, [1, 2, 42])

In [58]:
i1, l1

(42, [1, 2])

# Context Managers
## Motivation and Usage

In [59]:
with open('temp.txt','w') as f:
    f.write('hello world\n')
    f.write('test file for context manager\n')

In [60]:
with open('temp.txt','r') as f:
    content = f.readlines()
content

['hello world\n', 'test file for context manager\n']

The *with* statement is a context manager which gives access to the specified resource (here a text file) in the following code block.

The main advantage is that the context manager automatically takes care of closing the resource when the code block is finished or there is an error.

In [61]:
try:
    f = open('temp.txt')
    content = f.readlines()
finally:
    f.close()
content

['hello world\n', 'test file for context manager\n']

Implementation without context manager would be significantly more complex (here 5 lines instead of 2 for the read part) and error-prone (e.g. if it is forgotten to implement the close command or if it is not in a finally block).

## Implementing Own Context Managers
https://stackabuse.com/python-context-managers/

In [62]:
class MyFileHandler:
    """only for illustration - redundant because Python's open already includes a 
    context manager"""
    def __init__(self, filename, kind='r'):
        self.filename = filename
        self.kind = kind
    def __enter__(self):
        self.file = open(self.filename, self.kind)
        print('file opened')
        return self.file
    def __exit__(self, *exc):
        self.file.close()
        print('file closed')

In [63]:
with MyFileHandler('temp.txt','r') as f:
    content = f.readlines()
    print('file read')
    raise Exception
content

file opened
file read
file closed


Exception: 

Context managers are implemented by defining the dunder methods

    __enter__(self)
    __exit__(self, *exc)
    
Note that in the example the file is closed even though an exception has been raised.

## Cleanup

In [74]:
from os import remove
remove('temp.txt')

Author: Benjamin Lungwitz