# Numpy

In [1]:
import numpy as np

## Construction of Numpy Arrays

In [2]:
a1 = np.array([1, 2, 3, 4])
a1, type(a1), a1.dtype

(array([1, 2, 3, 4]), numpy.ndarray, dtype('int64'))

In [3]:
a_2d = np.array([[1, 2], [3, 4], [5, 6]])
a_2d

array([[1, 2],
       [3, 4],
       [5, 6]])

In [4]:
a_3d = np.array([[[1, 2], [3, 4], [5, 6]], [[1, 2], [3, 4], [5, 6]]])
a_3d

array([[[1, 2],
        [3, 4],
        [5, 6]],

       [[1, 2],
        [3, 4],
        [5, 6]]])

Numpy arrays can be defined in multiple dimensions.

### Data Types

In [5]:
a2 = np.array([1.1, 2, 3, 4.4])
a2, type(a2), a2.dtype

(array([1.1, 2. , 3. , 4.4]), numpy.ndarray, dtype('float64'))

In [6]:
a3 = np.array([1.1, 2, 3, 4.4, 'hello'])
a3, type(a3), a3.dtype

(array(['1.1', '2', '3', '4.4', 'hello'], dtype='<U32'),
 numpy.ndarray,
 dtype('<U32'))

The most basic way to construct numpy arrays is from lists (or any other iterable) using 

    np.array(iterable).

A numpy array is of a single type (in contrast to a list, which may contain different data types). If an array is defined with multiple types, they are casted to the most general type (e.g. int to float, numbers to strings).

### Generation from Comprehensions

In [7]:
aa1 = np.array([i**2 for i in range(100)]) # from list
aa1

array([   0,    1,    4,    9,   16,   25,   36,   49,   64,   81,  100,
        121,  144,  169,  196,  225,  256,  289,  324,  361,  400,  441,
        484,  529,  576,  625,  676,  729,  784,  841,  900,  961, 1024,
       1089, 1156, 1225, 1296, 1369, 1444, 1521, 1600, 1681, 1764, 1849,
       1936, 2025, 2116, 2209, 2304, 2401, 2500, 2601, 2704, 2809, 2916,
       3025, 3136, 3249, 3364, 3481, 3600, 3721, 3844, 3969, 4096, 4225,
       4356, 4489, 4624, 4761, 4900, 5041, 5184, 5329, 5476, 5625, 5776,
       5929, 6084, 6241, 6400, 6561, 6724, 6889, 7056, 7225, 7396, 7569,
       7744, 7921, 8100, 8281, 8464, 8649, 8836, 9025, 9216, 9409, 9604,
       9801])

In [9]:
aa2 = np.fromiter((i**2 for i in range(100)), dtype=np.int32) # from iterable object
aa2

array([   0,    1,    4,    9,   16,   25,   36,   49,   64,   81,  100,
        121,  144,  169,  196,  225,  256,  289,  324,  361,  400,  441,
        484,  529,  576,  625,  676,  729,  784,  841,  900,  961, 1024,
       1089, 1156, 1225, 1296, 1369, 1444, 1521, 1600, 1681, 1764, 1849,
       1936, 2025, 2116, 2209, 2304, 2401, 2500, 2601, 2704, 2809, 2916,
       3025, 3136, 3249, 3364, 3481, 3600, 3721, 3844, 3969, 4096, 4225,
       4356, 4489, 4624, 4761, 4900, 5041, 5184, 5329, 5476, 5625, 5776,
       5929, 6084, 6241, 6400, 6561, 6724, 6889, 7056, 7225, 7396, 7569,
       7744, 7921, 8100, 8281, 8464, 8649, 8836, 9025, 9216, 9409, 9604,
       9801], dtype=int32)

### Built-in Generator Functions

In [11]:
np.zeros([4, 2])

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [12]:
np.ones(5, dtype=np.int32)

array([1, 1, 1, 1, 1], dtype=int32)

In [13]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [14]:
aa3 = np.arange(100)**2 # first gererate array with numbers, then square element-wise
aa3

array([   0,    1,    4,    9,   16,   25,   36,   49,   64,   81,  100,
        121,  144,  169,  196,  225,  256,  289,  324,  361,  400,  441,
        484,  529,  576,  625,  676,  729,  784,  841,  900,  961, 1024,
       1089, 1156, 1225, 1296, 1369, 1444, 1521, 1600, 1681, 1764, 1849,
       1936, 2025, 2116, 2209, 2304, 2401, 2500, 2601, 2704, 2809, 2916,
       3025, 3136, 3249, 3364, 3481, 3600, 3721, 3844, 3969, 4096, 4225,
       4356, 4489, 4624, 4761, 4900, 5041, 5184, 5329, 5476, 5625, 5776,
       5929, 6084, 6241, 6400, 6561, 6724, 6889, 7056, 7225, 7396, 7569,
       7744, 7921, 8100, 8281, 8464, 8649, 8836, 9025, 9216, 9409, 9604,
       9801])

In [16]:
np.random.rand(10, 2) # 2d array with random numbers between 0 and 1

array([[0.81144398, 0.56012461],
       [0.64444993, 0.39449893],
       [0.90903228, 0.17020378],
       [0.85816314, 0.01502768],
       [0.62957997, 0.88286177],
       [0.94191483, 0.55001479],
       [0.14609678, 0.0722058 ],
       [0.59469333, 0.22019837],
       [0.33453561, 0.01873267],
       [0.46607953, 0.17129013]])

In [17]:
np.random.randn(4, 2, 2) # 3d array with normal distributed random numbers

array([[[ 1.75852272, -0.34642621],
        [ 0.10698502, -0.99888109]],

       [[-0.13570185, -0.49105757],
        [ 1.22015992, -0.2402027 ]],

       [[-0.02035728, -0.98723156],
        [-0.04973857,  0.43454007]],

       [[-0.05328922, -0.66412204],
        [ 0.57048852,  1.2253391 ]]])

Numpy offers a wide range of built-in functions or array generation, which are well optimized.

## Calculation

In [18]:
a = np.arange(3)
a

array([0, 1, 2])

In [19]:
M = np.array([[1, 2], [3, 4], [5, 6]])
M

array([[1, 2],
       [3, 4],
       [5, 6]])

In [20]:
M2 = np.array([[1, 2, -1], [3, 4, -3], [5, 6, -5]])
M2

array([[ 1,  2, -1],
       [ 3,  4, -3],
       [ 5,  6, -5]])

### Element-wise Operations

In [21]:
2*a + 7

array([ 7,  9, 11])

In [22]:
M**3

array([[  1,   8],
       [ 27,  64],
       [125, 216]])

### Matrix Operations

In [23]:
a @ M # matrix product

array([13, 16])

In [24]:
M.transpose()

array([[1, 3, 5],
       [2, 4, 6]])

### Column and Row Vectors

Mathematical definitions (recap):

Column vector $(n, 1)$:
$$x = \left(
\begin{array}{c}
x_1\\
x_2\\
...\\
x_n\\
\end{array}
\right)$$

Row vector $(1, m)$:
$$ x = (x_1, x_2, ..., x_m)$$

Matrix $(n, m)$:
$$A =\left(
\begin{array}{c}
a_{1,1}, a_{1,2}, ..., a_{1,m}\\
x_{2,1}, a_{2,2}, ..., a_{2,m}\\
...\\
a_{n,1}, a_{n,2}, ..., a_{n,m}\\
\end{array}
\right)$$

Matrix multiplication: 
$$A @ B = C$$
so that element-wise
$$c_{i,j} = \sum_{k=1}^{m}{a_{i,k} b_{k,j}}$$
Dimensions:
$$(n, m) @ (m, p) -> (n, p)$$

In [25]:
a, a.shape

(array([0, 1, 2]), (3,))

In [26]:
a.transpose(), a.transpose().shape, a == a.transpose()

(array([0, 1, 2]), (3,), array([ True,  True,  True]))

In [27]:
M.shape, M.T.shape

((3, 2), (2, 3))

In [28]:
a @ M # here a acts as a (1,n) matrix, i.e. a row vector

array([13, 16])

In [29]:
M.T @ a # here a acts as a (n, 1) matrix, i.e. a column vector

array([13, 16])

In [30]:
a @ a # here the 1st a is a row vector and the second one a column vector

5

For 2d arrays (matrices) the 1st dimension is the row and the 2nd the column.

1d numpy arrays have no information if they are row or column vectors. 
In calculations (e.g. matrix multiplications) they behave either like row or column vectors, as required by the operation to have matching dimensionalities (this mechanism is called *broadcasting*).

### Eigenvalues and Eigenvectors

In [31]:
eigenvals, eigenvecs = np.linalg.eig(M2)
eigenvals, eigenvecs

(array([-2.0000000e+00,  2.0000000e+00,  7.5678814e-16]),
 array([[-2.28983499e-16, -3.71390676e-01,  7.07106781e-01],
        [-4.47213595e-01, -5.57086015e-01,  1.43901351e-15],
        [-8.94427191e-01, -7.42781353e-01,  7.07106781e-01]]))

In [32]:
for i, ev in enumerate(eigenvals):
    print((M2 - ev * np.eye(3)) @ eigenvecs[:,i])

[-2.22044605e-16  1.33226763e-15  1.77635684e-15]
[-2.22044605e-16 -4.44089210e-16 -8.88178420e-16]
[ 3.24514059e-16 -4.61194906e-16 -2.02405999e-15]


### Descriptions

In [33]:
M.sum(), M.min(), M.max(), M.mean(), M.shape, M.size

(21, 1, 6, 3.5, (3, 2), 6)

In [34]:
np.sum(M), np.min(M), np.max(M), np.mean(M), np.shape(M), np.size(M)

(21, 1, 6, 3.5, (3, 2), 6)

## Performance

### Generation

In [8]:
%timeit aa1 = np.array([i**2 for i in range(100000)])

78.7 ms ± 34.9 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [10]:
%timeit aa2 = np.fromiter((i**2 for i in range(100000)), dtype=np.int32)

66.7 ms ± 58.4 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


Defining a numpy array from generator comprehension is only marginally slower than from list comprehension.

In [15]:
%timeit aa3 = np.arange(100000)**2

525 µs ± 2.72 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


Generating an array from numpy arange and squaring it afterwards is ca. 100 times faster than generating it from list or generator comprehensions.

### Summation

In [100]:
np_array = np.random.randn(100000)
array_list = list(np_array)

In [107]:
%timeit np_array.sum() # numpy sum using array method

131 µs ± 566 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [106]:
%timeit np.sum(np_array) # numpy sum using numpy function

151 µs ± 278 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [103]:
%timeit sum(array_list) # Python standard library sum on list

18.6 ms ± 48.2 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [111]:
%timeit np.sum(array_list) # numpy sum on list

16.8 ms ± 16.5 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [105]:
%timeit sum(np_array) # Python standard library sum on numpy array

32 ms ± 44.2 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


Ordered by decending execution time.

The numpy sum on numpy array is ca. 100 times faster than sums on Python arrays.

### Simple Element-wise Calculations

In [45]:
%timeit np.log(np_array**2 + 42)

5.38 ms ± 4.93 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [47]:
import math

In [48]:
%timeit [math.log(x**2 + 42) for x in array_list]

192 ms ± 1.01 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


Again, numpy is much faster than using a Python list. In addition, the numpy syntax is much simpler because there is no need for a loop.

### Speed up Calculations with Numba

Example from
https://numba.pydata.org/numba-doc/dev/user/5minguide.html

In [91]:
x = np.arange(10000).reshape(100, 100)

In [92]:
def slow(a):
    trace = 0
    for i in range(a.shape[0]):
        trace += np.tanh(a[i, i])
    return a + trace

In [93]:
%timeit slow(x)

854 µs ± 2.7 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [112]:
from numba import njit

In [121]:
@jit(nopython=True) # Set "nopython" mode for best performance, equivalent to @njit
def go_fast(a): # Function is compiled to machine code when called the first time
    trace = 0
    for i in range(a.shape[0]):   # Numba likes loops
        trace += np.tanh(a[i, i]) # Numba likes NumPy functions
    return a + trace              # Numba likes NumPy broadcasting

In [122]:
%timeit go_fast(x)

The slowest run took 5.04 times longer than the fastest. This could mean that an intermediate result is being cached.
34.3 µs ± 30.4 µs per loop (mean ± std. dev. of 7 runs, 1 loop each)


Numba is a just-in-time compiler working together with numpy. It could speed up complex calculations (especially involving large loops) siginificantly (in this example more than a factor of 20).
The first call of the method is slow because the complilation takes place, speed up is only possible for all following calls.

Note that numba supports only a fraction of Python code (especially simple calculations and most parts of numpy). If *nopython=True* (recommended setting), an exception is raised if non-supported code is compiled.

### Performance Summary

* Use numpy arrays and the corresponding numpy methods for large data
* For operations which cannot be expressed with numpy methods consider compiling with numba.